Repository DenilsonAP/devops-aula07, pull requests merged in 2018-09, with the labels that each got.

#4 V1.0 programacao
  src/jogovelha.py
Labels: Programação

#6 Create src/testes_inic.py
  src/testes_inic.py
Labels: Teste

#7 Gerar release v1.0
  docs/requisitos.md
  src/jogovelha.py
  src/testes_inic.py
Labels: Operações

#9 v1.1-analise
  docs/requisitos.md
Labels: Analise

#13 Create src/jogovelha.py
  src/jogovelha.py
Labels: Programação

#15 Integrar testes v1.0
  src/testes_inic.py
Labels: Teste
